import TopProductCard from './TopProductCard'
import ProductRankItem from './ProductRankItem'

export default function ProductResults({ rankedProducts = [], topProduct, condition }) {
  const sorted = [...rankedProducts].sort((a, b) => a.rank - b.rank)
  const others = sorted.slice(1)

  return (
    <div className="space-y-4">
      <TopProductCard product={topProduct} condition={condition} />

      {others.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-sm font-semibold text-slate-700">Other Options</h3>
          {others.map(product => (
            <ProductRankItem key={product.product_id ?? product.rank} product={product} />
          ))}
        </div>
      )}

      <p className="text-xs text-slate-400 text-center">
        Product suggestions are generated by AI from publicly available review data. Not a medical
        endorsement. Individual results will vary.
      </p>
    </div>
  )
}
